### ISSUE TITLE
trust the server list?

### ISSUE THREAD

**Issue by psjbeisler** [valeriansaliou/providence#2]
would using the vcards from the xmpp.net for "trusted" or some kind of karma reputation or authentication be useful?
https://github.com/stpeter/xmppdotnet

The downside is it would rely on an outside list of course, but "in theory" these are admins that took the time to "register" in a sense and are being promoted to the public. (the later being more important)

Not that this is all inclusive but in terms of a score value, it could be useful i suppose considering they do some type of verification first. (just an email)

**Comment by valeriansaliou** [comment]
Do you have any insights on the % of XMPP servers from the total number of legitimate servers in the federation that are listed here? Just making sure that most servers are listed here; and not only some minority.

Also, it would break the true decentralized nature of Providence; really don't want to rely on a central authority for this.

**Comment by psjbeisler** [comment]
i posted the question at first before you had defined it as decentralized
> Thus, Providence SHALL NOT make any active c2s/s2s checks to the remote server/user (eg: while verifying that the remote user answers to Entity Capabilities requests would be great for filtering purposes, it's not that great of an idea).

and stay hidden

**Comment by valeriansaliou** [comment]
True, that's something I am still unsure of; after all active checks are needed, it's just that Entity Capabilities are unreliable as they can be easily spoofed by spammers. Easy to code some Lua modules for Prosody to auto-answer to Caps. w/ information that look fine eg. Gajim, Adium, others.

**Comment by psjbeisler** [comment]
my concern is a possible dos due to a false positive. since every server will only realy build a relationship of trust with other servers it interacts with, they will all be seen differently.
